# Generated by Django 4.2.8 on 2023-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='course/author'),
        ),
    ]
