# Generated by Django 4.2.8 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursesubscription_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
    ]
